sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t amadinathaniel/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true amadinathaniel/react-test npm test

after_success: 
  - docker build -t amadinathaniel/multi-client ./client
  - docker build -t amadinathaniel/multi-nginx ./nginx
  - docker build -t amadinathaniel/multi-server ./server
  - docker build -t amadinathaniel/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push amadinathaniel/multi-client
  - docker push amadinathaniel/multi-nginx
  - docker push amadinathaniel/multi-server
  - docker push amadinathaniel/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-514385196167'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY